apps/cms/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings
from . import course_views

app_name = 'cms'
urlpatterns = [
    path('', views.index, name='index'),
    path('write_news/', views.WriteNewsView.as_view(), name='write_news'),
    path('edit_news/', views.EditNewsView.as_view(), name='edit_news'),
    path('news_category/', views.news_category, name='news_category'),
    path('add_news_category/', views.add_news_category, name='add_news_category'),
    path('edit_news_category/', views.edit_news_category, name='edit_news_category'),
    path('delete_news_category/', views.delete_news_category, name='delete_news_category'),
    path('upload_file/', views.upload_file, name='upload_file'),
    path('qntoken/', views.qntoken, name='qntoken'),
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

# 这是课程相关的url映射
urlpatterns += [
    path('pub_course/',course_views.PubCourse.as_view(),name='pub_course')
]

apps/xfzauth/urls.py
from django.urls import path
from . import views

app_name= 'xfzauth'
urlpatterns = [
    path('login/',views.login_views,name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('img_captcha/', views.img_captcha, name='img_captcha'),
    path('sms_captcha/', views.sms_captcha, name='sms_captcha'),
    path('register/', views.register, name='register'),
]

xfz/urls.py
from django.contrib import admin
from django.urls import path,include
from apps.news import views
from django.conf import settings

urlpatterns = [
    path('', views.index,name='index'),
    path('search/', views.search, name='search'),
    path('news/', include('apps.news.urls')),
    path('cms/', include('apps.cms.urls')),
    path('account/', include('apps.xfzauth.urls')),
    path('course/', include('apps.course.urls')),
    path('payinfo/', include('apps.payinfo.urls')),
    path('ueditor/', include('apps.ueditor.urls')),

]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns.append(path('__debug__/',include(debug_toolbar.urls)))

apps/cms/models.py
from django.db import models

# Create your models here.


# python manage.py makemigrations   生成迁移脚本文件
# python manage.py migrate 把新生成的迁移脚本文件映射到数据库中

apps/cms/forms.py
from apps.forms import FormMimin
from django import forms
from apps.news.models import News
from apps.course.models import Course


class EditNewsCategoryForm(forms.Form):
    pk = forms.IntegerField()
    name = forms.CharField(max_length=100)


class EditNewsForm(forms.ModelForm, FormMimin):
    category = forms.IntegerField()
    pk = forms.IntegerField()

    class Meta:
        model = News
        exclude = ['category', 'author', 'pub_time']


class WriteNewsForm(forms.ModelForm, FormMimin):
    category = forms.IntegerField()

    # pk = forms.IntegerField()

    class Meta:
        model = News
        exclude = ['category', 'author', 'pub_time']


class PubCourseForm(forms.ModelForm, FormMimin):
    category_id = forms.IntegerField()
    teacher_id = forms.IntegerField()

    class Meta:
        model = Course
        exclude = ("category", 'teacher')

apps/cms/views.py
from django.shortcuts import render
from django.views.generic import View
from django.views.decorators.http import require_POST,require_GET
from apps.news.models import NewsCategory,News
from utils import restful
from .forms import EditNewsCategoryForm,WriteNewsForm, EditNewsForm
import os
from django.conf import settings
import qiniu

# Create your views here.

def index(request):
    return render(request, 'cms/index.html')


class WriteNewsView(View):
    def get(self,request):
        categories = NewsCategory.objects.all()
        context = {
            'categories': categories
        }
        return render(request,'cms/write_news.html',context=context)
    def post(self,request):
        form=WriteNewsForm(request.POST)

        if form.is_valid():
            title=form.cleaned_data.get('title')
            desc=form.cleaned_data.get('desc')
            thumbnail=form.cleaned_data.get('thumbnail')
            content=form.cleaned_data.get('content')
            category_id=form.cleaned_data.get('category')
            category=NewsCategory.objects.get(pk=category_id)
            print(str(title))
            print(str(desc))
            print(str(thumbnail))
            print(str(content))
            print(str(category_id))
            print(str(category))

            News.objects.create(title=title,desc=desc,thumbnail=thumbnail,content=content,category=category,author=request.user)
            return restful.ok()
        else:
            print(str(form.get_errors()))
            return restful.params_error(message=form.get_errors())


class EditNewsView(View):
    def get(self,request):
        news_id = request.GET.get('news_id')
        news = News.objects.get(pk=news_id)
        context = {
            'news': news,
            'categories': NewsCategory.objects.all()
        }
        self.render = render(request, 'cms/write_news.html', context=context)
        return self.render

    def post(self,request):
        form = EditNewsForm(request.POST)
        if form.is_valid():
            title = form.cleaned_data.get('title')
            desc = form.cleaned_data.get('desc')
            thumbnail = form.cleaned_data.get('thumbnail')
            content = form.cleaned_data.get('content')
            category_id = form.cleaned_data.get('category')
            pk = form.cleaned_data.get("pk")
            category = NewsCategory.objects.get(pk=category_id)
            News.objects.filter(pk=pk).update(title=title,desc=desc,thumbnail=thumbnail,content=content,category=category)
            return restful.ok()
        else:
            return restful.params_error(message=form.get_errors())


@require_GET
def news_category(request):
    categories = NewsCategory.objects.all()
    context={
        'categories':categories
    }
    return render(request,'cms/news_category.html',context=context)


@require_POST
def add_news_category(request):
    name = request.POST.get('name')
    exists = NewsCategory.objects.filter(name=name).exists()
    if not exists:
        NewsCategory.objects.create(name=name)
        return restful.ok()
    else:
        return restful.params_error(message='该分类已经存在！')


@require_POST
def edit_news_category(request):
    form = EditNewsCategoryForm(request.POST)
    if form.is_valid():
        pk = form.cleaned_data.get('pk')
        name = form.cleaned_data.get('name')
        try:
            NewsCategory.objects.filter(pk=pk).update(name=name)
            return restful.ok()
        except:
            return restful.params_error(message='该新闻分类不存在')
    else:
        return restful.params_error(message=form.get_error())


@require_POST
def delete_news_category(request):
    pk=request.POST.get('pk')
    try:
        NewsCategory.objects.filter(pk=pk).delete()
        return restful.ok()
    except:
        return restful.unauth(message='该分类不存在')

@require_POST
def upload_file(request):
    file=request.FILES.get('file')
    name=file.name
    with open(os.path.join(settings.MEDIA_ROOT,name),'wb') as fp:
        for chunk in file.chunks():
            fp.write(chunk)
    url=request.build_absolute_uri(settings.MEDIA_URL+name)
    print(str(url))
    return restful.result(data={'url':url})


@require_GET
def qntoken(request):
    access_key= settings.QINIU_ACCESS_KEY
    secret_key= settings.QINIU_SECRET_KEY
    bucket= settings.QINIU_BUCKET_NAME

    q=qiniu.Auth(access_key,secret_key)
    token=q.upload_token(bucket)
    return restful.result(data={'token':token})

front/templates/cms/base.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>{% block title %}{% endblock %} | 后台管理系统</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <!-- Bootstrap 3.3.7 -->
    <link rel="stylesheet" href="{% static 'AdminLTE-2.4.10/bower_components/bootstrap/dist/css/bootstrap.min.css' %}">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="{% static 'AdminLTE-2.4.10/bower_components/font-awesome/css/font-awesome.min.css' %}">
    <!-- Ionicons -->
    <link rel="stylesheet" href="{% static 'AdminLTE-2.4.10/bower_components/Ionicons/css/ionicons.min.css' %}">
    <!-- Theme style -->
    <link rel="stylesheet" href="{% static 'AdminLTE-2.4.10/dist/css/AdminLTE.min.css' %}">
    <!-- AdminLTE Skins. Choose a skin from the css/skins
         folder instead of downloading all of them to reduce the load. -->
    <link rel="stylesheet" href="{% static 'AdminLTE-2.4.10/dist/css/skins/_all-skins.min.css' %}">
    <link rel="stylesheet" href="{% static 'sweetalert/sweetalert.css' %}">
    <!-- Morris chart -->
    <link rel="stylesheet" href="{% static 'AdminLTE-2.4.10/bower_components/morris.js/morris.css' %}">
    <!-- jvectormap -->
    <link rel="stylesheet" href="{% static 'AdminLTE-2.4.10/bower_components/jvectormap/jquery-jvectormap.css' %}">
    <!-- Date Picker -->
    <link rel="stylesheet"
          href="{% static 'AdminLTE-2.4.10/bower_components/bootstrap-datepicker/dist/css/bootstrap-datepicker.min.css' %}">
    <!-- Daterange picker -->
    <link rel="stylesheet"
          href="{% static 'AdminLTE-2.4.10/bower_components/bootstrap-daterangepicker/daterangepicker.css' %}">
    <!-- bootstrap wysihtml5 - text editor -->
    <link rel="stylesheet"
          href="{% static 'AdminLTE-2.4.10/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.min.css' %}">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->
    {% block head %}

    {% endblock %}
</head>
<body class="hold-transition skin-blue sidebar-mini">
<div class="wrapper">

    <header class="main-header">
        <!-- Logo -->
        <a href="index2.html" class="logo">
            <!-- mini logo for sidebar mini 50x50 pixels -->
            <span class="logo-mini"><b>CMS</b></span>
            <!-- logo for regular state and mobile devices -->
            <span class="logo-lg"><b>小饭桌</b>后台管理系统</span>
        </a>
        <!-- Header Navbar: style can be found in header.less -->
        <nav class="navbar navbar-static-top">
            <!-- Sidebar toggle button-->
            <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
                <span class="sr-only">Toggle navigation</span>
            </a>

            <div class="navbar-custom-menu">
                <ul class="nav navbar-nav">
                    <!-- User Account: style can be found in dropdown.less -->
                    <li class="dropdown user user-menu">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            <img src="http://img.52z.com/upload/news/image/20180129/20180129082228_25779.jpg"
                                 class="user-image" alt="User Image">
                            <span class="hidden-xs">{{ user.username }}</span>
                        </a>
                        <ul class="dropdown-menu">
                            <!-- User image -->
                            <li class="user-header">
                                <img src="http://img.52z.com/upload/news/image/20180129/20180129082228_25779.jpg"
                                     class="img-circle" alt="User Image">
                                <p>
                                    Python Web和高级爬虫工程师
                                    <small>Member since Nov. 2019</small>
                                </p>
                            </li>
                            <!-- Menu Body -->
                            <li class="user-body">
                            </li>
                            <!-- Menu Footer-->
                            <li class="user-footer">
                                <div class="pull-left">
                                    <a href="#" class="btn btn-default btn-flat">个人中心</a>
                                </div>
                                <div class="pull-right">
                                    <a href="#" class="btn btn-default btn-flat">注销</a>
                                </div>
                            </li>
                        </ul>
                    </li>
                </ul>
            </div>
        </nav>
    </header>
    <!-- Left side column. contains the logo and sidebar -->
    <aside class="main-sidebar">
        <!-- sidebar: style can be found in sidebar.less -->
        <section class="sidebar">
            <!-- Sidebar user panel -->
            <div class="user-panel">
            </div>
            <!-- search form -->
            <form action="#" method="get" class="sidebar-form">
                <div class="input-group">
                    <input type="text" name="q" class="form-control" placeholder="查找">
                    <span class="input-group-btn">
                <button type="submit" name="search" id="search-btn" class="btn btn-flat"><i class="fa fa-search"></i>
                </button>
              </span>
                </div>
            </form>
            <!-- /.search form -->
            <!-- sidebar menu: : style can be found in sidebar.less -->
            <ul class="sidebar-menu" data-widget="tree">
                <li class="active">
                    <a href="{% url 'cms:index' %}">
                        <i class="fa fa-home"></i> <span>首页</span>
                    </a>
                </li>
                <li class="header">新闻管理</li>
                <li>
                    <a href="{% url 'cms:write_news' %}">
                        <i class="fa fa-edit"></i>
                        <span>发布新闻</span>
                    </a>
                </li>
                <li>
                    <a href="{% url 'cms:news_category' %}">
                        <i class="fa fa-tag"></i>
                        <span>新闻分类</span>
                    </a>
                </li>
                <li class="header">课程管理</li>
                <li>
                    <a href="{% url 'cms:pub_course' %}">
                        <i class="fa fa-tv"></i>
                        <span>发布课程</span>
                    </a>
                </li>
            </ul>
        </section>
        <!-- /.sidebar -->
    </aside>

    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            {% block content-header %}
            {% endblock %}
        </section>
        <section class="content">
            {% block content %}
            {% endblock %}
        </section>
    </div>
    <!-- /.content-wrapper -->
    <footer class="main-footer">
        <strong>小饭桌</strong>CMS后台管理系统
    </footer>

</div>
<!-- ./wrapper -->

<!-- jQuery 3 -->
<script src="{% static 'AdminLTE-2.4.10/bower_components/jquery/dist/jquery.min.js' %}"></script>
<!-- jQuery UI 1.11.4 -->
<script src="{% static 'AdminLTE-2.4.10/bower_components/jquery-ui/jquery-ui.min.js' %}"></script>
<script src="{% static 'js/message.min.js' %}"></script>
<script src="{% static 'sweetalert/sweetalert.min.js' %}"></script>
<script src="{% static 'js/xfzajax.js' %}"></script>
<script src="{% static 'js/xfzalert.js' %}"></script>
<!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
<script>
    $.widget.bridge('uibutton', $.ui.button);
</script>
<!-- Bootstrap 3.3.7 -->
<script src="{% static 'AdminLTE-2.4.10/bower_components/bootstrap/dist/js/bootstrap.min.js' %}"></script>
<!-- Morris.js charts -->
<script src="{% static 'AdminLTE-2.4.10/bower_components/raphael/raphael.min.js' %}"></script>
<script src="{% static 'AdminLTE-2.4.10/bower_components/morris.js/morris.min.js' %}"></script>
<!-- Sparkline -->
<script src="{% static 'AdminLTE-2.4.10/bower_components/jquery-sparkline/dist/jquery.sparkline.min.js' %}"></script>
<!-- jvectormap -->
<script src="{% static 'AdminLTE-2.4.10/plugins/jvectormap/jquery-jvectormap-1.2.2.min.js' %}"></script>
<script src="{% static 'AdminLTE-2.4.10/plugins/jvectormap/jquery-jvectormap-world-mill-en.js' %}"></script>
<!-- jQuery Knob Chart -->
<script src="{% static 'AdminLTE-2.4.10/bower_components/jquery-knob/dist/jquery.knob.min.js' %}"></script>
<!-- daterangepicker -->
<script src="{% static 'AdminLTE-2.4.10/bower_components/moment/min/moment.min.js' %}"></script>
<script src="{% static 'AdminLTE-2.4.10/bower_components/bootstrap-daterangepicker/daterangepicker.js' %}"></script>
<!-- datepicker -->
<script src="{% static 'AdminLTE-2.4.10/bower_components/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js' %}"></script>
<!-- Bootstrap WYSIHTML5 -->
<script src="{% static 'AdminLTE-2.4.10/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.all.min.js' %}"></script>
<!-- Slimscroll -->
<script src="{% static 'AdminLTE-2.4.10/bower_components/jquery-slimscroll/jquery.slimscroll.min.js' %}"></script>
<!-- FastClick -->
<script src="{% static 'AdminLTE-2.4.10/bower_components/fastclick/lib/fastclick.js' %}"></script>
<!-- AdminLTE App -->
<script src="{% static 'AdminLTE-2.4.10/dist/js/adminlte.min.js' %}"></script>
<!-- AdminLTE dashboard demo (This is only for demo purposes) -->
<script src="{% static 'AdminLTE-2.4.10/dist/js/pages/dashboard.js' %}"></script>
<!-- AdminLTE for demo purposes -->
<script src="{% static 'AdminLTE-2.4.10/dist/js/demo.js' %}"></script>
</body>
</html>

front/templates/cms/index.html
{% extends 'cms/base.html' %}

{% block title %}
首页
{% endblock %}

{% block content-header %}
<h1>欢迎来到小饭桌CMS管理系统</h1>
{% endblock %}

front/templates/cms/login.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>小饭桌CMS后台管理系统|登录</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
  <!-- Bootstrap 3.3.7 -->
  <link rel="stylesheet" href="{% static 'adminlte/bower_components/bootstrap/dist/css/bootstrap.min.css' %}">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="{% static 'adminlte/bower_components/font-awesome/css/font-awesome.min.css' %}">
  <!-- Ionicons -->
  <link rel="stylesheet" href="{% static 'adminlte/bower_components/Ionicons/css/ionicons.min.css' %}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{% static 'adminlte/dist/css/AdminLTE.min.css' %}">
  <!-- iCheck -->
  <link rel="stylesheet" href="{% static 'adminlte/plugins/iCheck/square/blue.css' %}">

  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->

  <!-- Google Font -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
</head>
<body class="hold-transition login-page">
<div class="login-box">
  <div class="login-logo">
    <a href="{% url 'cms:login' %}">小饭桌CMS管理系统</a>
  </div>
  <!-- /.login-logo -->
  <div class="login-box-body">
    <p class="login-box-msg">请登录</p>

    <form action="{% url 'xfzauth:login' %}" method="post">
        {% csrf_token %}
      <div class="form-group has-feedback">
        <input type="text" class="form-control" placeholder="手机号码" name="telephone">
        <span class="glyphicon glyphicon-envelope form-control-feedback"></span>
      </div>
      <div class="form-group has-feedback">
        <input type="password" class="form-control" placeholder="密码" name="password">
        <span class="glyphicon glyphicon-lock form-control-feedback"></span>
      </div>
      <div class="row">
        <div class="col-xs-8">
          <div class="checkbox icheck">
            <label>
              <input type="checkbox" name="remenber" value="1"> 记住我
            </label>
          </div>
        </div>
        <!-- /.col -->
        <div class="col-xs-4">
          <button type="submit" class="btn btn-primary btn-block btn-flat">登录</button>
        </div>
        <!-- /.col -->
      </div>
    </form>
  </div>
  <!-- /.login-box-body -->
</div>
<!-- /.login-box -->

<!-- jQuery 3 -->
<script src="{% static 'adminlte/bower_components/jquery/dist/jquery.min.js' %}"></script>
<!-- Bootstrap 3.3.7 -->
<script src="{% static 'adminlte/bower_components/bootstrap/dist/js/bootstrap.min.js' %}"></script>
<!-- iCheck -->
<script src="{% static 'adminlte/plugins/iCheck/icheck.min.js' %}"></script>
<script>
  $(function () {
    $('input').iCheck({
      checkboxClass: 'icheckbox_square-blue',
      radioClass: 'iradio_square-blue',
      increaseArea: '20%' /* optional */
    });
  });
</script>
</body>
</html>

front/templates/cms/news_category.html
{% extends 'cms/base.html' %}

{% block title %}
    新闻分类
{% endblock %}

{% block head %}
    <script src="{% static 'AdminLTE-2.4.10/bower_components/jquery/dist/jquery.min.js' %}"></script>
    <script src="{% static 'js/news_category.js' %}"></script>
{% endblock %}

{% block content-header %}
    <h1>新闻分类</h1>
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-12">
            <div class="box box-primary">
                <div class="box-header">
                    <button class="btn btn-primary pull-right" id="add-btn">添加分类</button>
                </div>
                <div class="box-body">
                    <table class="table table-bordered">
                        <thead>
                        <tr>
                            <th>分类名称</th>
                            <th>新闻数量</th>
                            <th>操作</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for category in categories %}
                            <tr data-pk="{{ category.pk }}" data-name="{{ category.name }}">
                                <td>{{ category.name }}</td>
                                <td>20</td>
                                <td>
                                    <button class="btn btn-warning btn-xs edit-btn">编辑</button>
                                    <button class="btn btn-danger btn-xs delete-btn">删除</button>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

front/templates/cms/pub_course.html
{% extends 'cms/base.html' %}

{% block title %}
    发布课程
{% endblock %}

{% block head %}
    <script src="{% static 'AdminLTE-2.4.10/bower_components/jquery/dist/jquery.min.js' %}"></script>
    <script src="{% static 'ueditor/ueditor.config.js' %}"></script>
    <script src="{% static 'ueditor/ueditor.all.min.js' %}"></script>
    <script src="{% static 'js/pub_course.js' %}"></script>
{% endblock %}

{% block content-header %}
<h1>发布课程</h1>
{% endblock %}

{% block content %}
<div class="row">
<div class="col-md-12">
    <div class="box">
        <div class="box-header">
            <div class="form-group">
                <label for="title-input">标题：</label>
                <input type="text" class="form-control" placeholder="课程标题" name="title" id="title-input">
            </div>
            <div class="form-group">
                <label for="category-input">分类：</label>
                <select name="category" class="form-control" id="category-input">
                    {% for category in categories %}
                        <option value="{{ category.pk }}">{{ category.name }}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="form-group">
                <label for="teacher-input">讲师：</label>
                <select name="teacher" id="teacher-input" class="form-control">
                    {% for teacher in teachers %}
                        <option value="{{ teacher.pk }}">{{ teacher.username }}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="form-group">
                <label for="video-input">视频地址：</label>
                <input type="text" class="form-control" name="video_url" id="video-input" placeholder="视频地址">
            </div>
            <div class="form-group">
                <label for="cover-input">封面图：</label>
                <input type="text" class="form-control" name="cover" id="cover-input" placeholder="封面图">
            </div>
            <div class="form-group">
                <label for="price-input">价格：</label>
                <input type="text" class="form-control" name="price" id="price-input" placeholder="价格">
            </div>
            <div class="form-group">
                <label for="duration-input">时长：</label>
                <input type="text" class="form-control" name="duration" id="duration-input">
            </div>
            <div class="form-group">
                <label>简介：</label>
                <script id="editor" type="text/plain"></script>
            </div>
            <div class="form-group">
                <button class="btn btn-primary pull-right" id="submit-btn">发布课程</button>
            </div>
        </div>
    </div>
</div>
</div>
{% endblock %}

front/templates/cms/write_news.html
{% extends 'cms/base.html' %}

{% block title %}
    发布新闻
{% endblock %}

{% block head %}
    <script src="https://unpkg.com/qiniu-js@2.5.2/dist/qiniu.min.js"></script>
    <script src="{% static 'AdminLTE-2.4.10/bower_components/jquery/dist/jquery.min.js' %}"></script>
    <script src="{% static 'ueditor/ueditor.config.js' %}"></script>
    <script src="{% static 'ueditor/ueditor.all.min.js' %}"></script>
    <script src="{% static 'js/write_news.js' %}"></script>
{% endblock %}

{% block content-header %}
    <h1>
    {% if news %}
        编辑新闻
    {% else %}
        发布新闻
    {% endif %}
    </h1>
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-12">
            <div class="box box-primary">
                <form action="" class="form">
                    <div class="box-body">
                        <div class="form-group">
                            <label for="title-form">标题</label>
                            {% if news %}
                                <input type="text" class="form-control" name="title" id="title-form" value="{{ news.title }}">                                            {% else %}
                                <input type="text" class="form-control" name="title" id="title-form">
                            {% endif %}
                        </div>
                        <div class="form-group">
                            <label for="category-form">分类</label>
                            <select name="category" id="category-form" class="form-control">
                                {% for category in categories %}
                                    {% if news and news.category_id == category.pk %}
                                        <option value="{{ category.pk }}" selected>{{ category.name }}</option>
                                    {% else %}
                                        <option value="{{ category.pk }}">{{ category.name }}</option>
                                    {% endif %}
                                {% endfor %}

                            </select>
                        </div>
                        <div class="form-group">
                            <label for="desc-form">描述</label>
                            {% if news %}
                                <input type="text" class="form-control" id="desc-form" name="desc" value="{{ news.desc }}">                                               {% else %}
                                <input type="text" class="form-control" id="desc-form" name="desc">
                            {% endif %}
                        </div>
                        <div class="form-group">
                            <label for="thumbnail-form">缩略图</label>
                            <div class="input-group">
                                {% if news %}
                                    <input type="text" class="form-control" id="thumbnail-form" name="thumbnail" value="{{ news.thumbnail }}">
                                {% else %}
                                    <input type="text" class="form-control" id="thumbnail-form" name="thumbnail">
                                {% endif %}
                                <span class="input-group-btn">
                                    <label class="btn btn-default btn-file">
                                        上传图片<input hidden type="file" class="btn btn-default" id="thumbnail-btn">
                                    </label>
                                </span>
                            </div>
                        </div>
                        <div id="progress-group" class="form-group" style="display: none;">
                            <div class="progress">
                                <div class="progress-bar progress-bar-success progress-bar-striped" role="progressbar"
                                     aria-valuenow="40" aria-valuemin="0" aria-valuemax="100" style="width: 0">
                                    0%
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="content-form">内容</label>
                            <script id="editor" type="text/plain">
                                {{ news.content|safe }}
                            </script>
                        </div>
                    </div>
                    <div class="box-footer">
                        <button id="submit-btn" data-news-id="{{ news.pk }}" class="btn btn-primary pull-right">发布新闻</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}