apps/news/urls.py
from django.urls import path
from . import views

app_name= 'news'
urlpatterns = [
    path('<int:news_id>/', views.new_detail, name='news_detail'),
    path('list/', views.news_list, name='news_list'),
    path('public_comment/', views.public_comment, name='public_comment'),

]

xfz/urls.py
from django.contrib import admin
from django.urls import path,include
from apps.news import views
from django.conf import settings

urlpatterns = [
    path('', views.index,name='index'),
    path('search/', views.search, name='search'),
    path('news/', include('apps.news.urls')),
    path('cms/', include('apps.cms.urls')),
    path('account/', include('apps.xfzauth.urls')),
    path('course/', include('apps.course.urls')),
    path('payinfo/', include('apps.payinfo.urls')),
    path('ueditor/', include('apps.ueditor.urls')),

]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns.append(path('__debug__/',include(debug_toolbar.urls)))

apps/news/models.py
from django.db import models


class NewsCategory(models.Model):
    name = models.CharField(max_length=100)


class News(models.Model):
    title = models.CharField(max_length=200)
    desc = models.CharField(max_length=200)
    thumbnail = models.URLField()
    content = models.TextField()
    pub_time=models.DateTimeField(auto_now_add=True)
    category = models.ForeignKey('NewsCategory',on_delete=models.SET_NULL,null=True)
    author = models.ForeignKey('xfzauth.User',on_delete=models.SET_NULL,null=True)

    class Meta:
        ordering=['-pub_time']


class Comment(models.Model):
    content = models.CharField(max_length=300)
    pub_time = models.DateTimeField(auto_now_add=True)
    news = models.ForeignKey("News",on_delete=models.CASCADE)
    author = models.ForeignKey("xfzauth.User",on_delete=models.CASCADE)

apps/news/forms.py
from django import forms
from apps.forms import FormMimin

class PublicCommentForm(forms.Form, FormMimin):
    content = forms.CharField()
    news_id = forms.IntegerField()

apps/news/views.py
from django.shortcuts import render
from .models import NewsCategory, News, Comment
from django.conf import settings
from .serializers import NewsSerializer,CommentSerizlizer
from utils import restful
from .forms import PublicCommentForm
from django.db.models import Q

def index(request):
    count = settings.ONE_PAGE_NEWS_COUNT
    newses = News.objects.select_related('category','author').all()[0:count]
    categories = NewsCategory.objects.all()
    context = {
        'newses':newses,
        'categories':categories
    }
    return render(request,'news/index.html',context=context)


def news_list(request):
    page = int(request.GET.get('p', 1))
    category_id = int(request.GET.get('category_id', 0))
    start = (page-1)*settings.ONE_PAGE_NEWS_COUNT
    end=start+settings.ONE_PAGE_NEWS_COUNT
    if category_id==0:
        newses = News.objects.select_related('category','author').all()[start:end]
    else:
        newses = News.objects.select_related('category','author').filter(category_id=category_id)[start:end]
    serializer = NewsSerializer(newses,many=True)
    data=serializer.data
    return restful.result(data=data)


def new_detail(request, news_id):
    news = News.objects.select_related('category','author').get(pk=news_id)

    context = {
        'news': news
    }
    return render(request, 'news/news_detail.html', context=context)


def search(request):
    q = request.GET.get('q')
    context = {}
    if q:
        newses = News.objects.filter(Q(title__icontains=q)|Q(content__icontains=q))
        context['newses'] = newses
    return render(request,'search/search.html',context=context)


def public_comment(request):
    form = PublicCommentForm(request.POST)
    if form.is_valid():
        news_id = form.cleaned_data.get('news_id')
        content = form.cleaned_data.get('content')

        news = News.objects.get(pk=news_id)
        comment = Comment.objects.create(content=content,news=news,author=request.user)
        serizlize = CommentSerizlizer(comment)
        return restful.result(data=serizlize.data)
    else:
        return restful.params_error(message=form.get_errors())

front/templates/news/index.html
{% extends 'base/front_base.html' %}
{% load news_filters %}
{% block title %}
    小饭桌
{% endblock %}
{% block head %}
    <link rel="stylesheet" href="{% static 'css/news/index.min.css' %}">
    <script src="{% static 'arttemplate/template-web.js' %}"></script>
    <script src="{% static 'js/index.js' %}"></script>
    <script id="news-item" type="text/html">
    {% verbatim %}
    {{ each newses news index }}
        <li>
                            <div class="thumbnail-group">
                                <a href="#">
                                    <img src="{{ news.thumbnail }}" alt="">
                                </a>
                            </div>
                            <div class="news-group">
                                <p class="title">
                                    <a href="#">{{ news.title }}</a>
                                </p>
                                <p class="desc">
                                    {{ news.desc }}
                                </p>
                                <p class="more">
                                   <span class="category">{{ news.category.name }}</span>
                                    <span class="pub-time">{{ news.pub_time}}</span>
                                    <span class="author">{{ news.author.username }}</span>
                                </p>
                            </div>
                        </li>
    {{ /each }}
    {% endverbatim %}

</script>
{% endblock %}
{% block main %}
    <div class="main">
        <div class="wrapper">
            <div class="main-content-wrapper">
                <div class="banner-group" id="banner-group">
                    <ul class="banner-ul" id="banner-ul">
                        <li>
                            <a href="#">
                                <img src="https://static-image.xfz.cn/1523588994_243.jpg" alt="">
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <img src="https://static-image.xfz.cn/1523504442_455.png" alt="">
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <img src="https://static-image.xfz.cn/1521444982_469.jpg" alt="">
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <img src="https://static-image.xfz.cn/1522742329_629.png" alt="">
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <img src="https://static-image.xfz.cn/1525669927_166.jpg" alt="">
                            </a>
                        </li>
                    </ul>
                    <span class="arrow left-arrow">‹</span>
                    <span class="arrow right-arrow">›</span>
                    <div class="page-control-group">
                        <ul class="page-control">
                        </ul>
                    </div>
                </div>
                <div class="list-outer-group">
                    <ul class="list-tab">
                    <li data-category="{{ category.pk }}"><a href="javascript:void(0)" class="active">最新资讯</a></li>
                        {% for category in categories %}
                            <li data-category="{{ category.pk }}"><a href="javascript:void(0)">{{ category.name }}</a></li>
                        {% endfor %}

                    </ul>
                    <ul class="list-inner-group">
                        {% for news in newses %}
                            <li>
                            <div class="thumbnail-group">
                                <a href="{% url 'news:news_detail' news_id=news.pk %}">
                                    <img src="{{ news.thumbnail }}" alt="">
                                </a>
                            </div>
                            <div class="news-group">
                                <p class="title">
                                    <a href="{% url 'news:news_detail' news_id=news.pk %}">{{ news.title }}</a>
                                </p>
                                <p class="desc">
                                    {{ news.desc }}
                                </p>
                                <p class="more">
                                   <span class="category">{{ news.category.name }}</span>
                                    <span class="pub-time">{{ news.pub_time|time_since }}</span>
                                    <span class="author">{{ news.author.username }}</span>
                                </p>
                            </div>
                        </li>
                        {% endfor %}



                    </ul>
                    <div class="load-more-group">
                        <button class="load-more" id="load-more-btn">查看更多</button>
                    </div>
                </div>
            </div>
            {% include 'common/sidebar.html' %}
        </div>
    </div>
{% endblock %}

front/templates/news/news_detail.html
{% extends 'base/front_base.html' %}
{% block title %}
新闻详情-小饭桌
{% endblock %}
{% load news_filters %}
{% block head %}
<link rel="stylesheet" href="{% static 'css/news/news_detail.min.css' %}">
    <script src="{% static 'arttemplate/template-web.js' %}"></script>
    <script src="{% static 'js/news_detail.js' %}"></script>
    <script id="comment-item" type="text/html">
        {% verbatim %}
        <li>
            <div class="comment-info">
                <img src="https://timgsa.baidu.com/timg?image&quality=80&size=b9999_10000&sec=1528129845916&di=536993042d5223862f8c4ab157ba6e72&imgtype=0&src=http%3A%2F%2Fpic1.ipadown.com%2Fimgs%2F201206120933354195.jpg"
                     alt="" class="avatar">
                <span class="author">{{ comment.author.username }}</span>
                <span class="pub-time">{{ comment.pub_time}}</span>
            </div>
            <p class="comment-content">{{ comment.content }}</p>
        </li>
        {% endverbatim %}
</script>
{% endblock %}
{% block main %}
<div class="main">
        <div class="wrapper">
            <div class="main-content-wrapper">
                <div class="news-wrapper">
                    <h1 class="title">{{ news.title }}</h1>
                    <div class="news-info">
                        <div class="info-group">
                            <span class="author">{{ news.anthor.username }}</span>
                            <span class="pub-time">{{ news.pub_time|time_since }}</span>
                            <span class="category">{{ news.category.name }}</span>
                        </div>
                        <div class="share-group">
                            <span>分享至：</span>
                            <a class="weixin share-item"></a>
                            <a href="#" class="weibo share-item"></a>
                        </div>
                    </div>
                    <article class="article">
                        {{ news.content | safe }}
                    </article>
                </div>
                <div class="comment-wrapper">
                    <h3 class="title">文章评论（0）</h3>
                    <textarea name="comment" class="comment-textarea logined-textarea" placeholder="立即登录，参与评论~"></textarea>
                    <div class="submit-btn-group">
                        <button class="submit-btn" data-news-id="{{ news.pk }}">立即评论</button>
                    </div>
                    <ul class="comment-list">
                        <li>
                            <div class="comment-info">
                                <img src="https://timgsa.baidu.com/timg?image&quality=80&size=b9999_10000&sec=1528129845916&di=536993042d5223862f8c4ab157ba6e72&imgtype=0&src=http%3A%2F%2Fpic1.ipadown.com%2Fimgs%2F201206120933354195.jpg" alt="" class="avatar">
                                <span class="author">小知了</span>
                                <span class="pub-time">1小时前</span>
                            </div>
                            <p class="comment-content">这是第一条评论</p>
                        </li>
                        <li>
                            <div class="comment-info">
                                <img src="https://timgsa.baidu.com/timg?image&quality=80&size=b9999_10000&sec=1528129845916&di=536993042d5223862f8c4ab157ba6e72&imgtype=0&src=http%3A%2F%2Fpic1.ipadown.com%2Fimgs%2F201206120933354195.jpg" alt="" class="avatar">
                                <span class="author">小知了</span>
                                <span class="pub-time">1小时前</span>
                            </div>
                            <p class="comment-content">这是第一条评论</p>
                        </li>
                    </ul>
                </div>
            </div>
            {% include 'common/sidebar.html' %}
        </div>
    </div>
{% endblock %}